export const ui = {
  en: {
    headerData: 'Header Data',
    reportName: 'Report name',
    orderNo: 'Order no',
    reportDateStart: 'Report date (start)',
    reportDateEnd: 'Report date (end)',
    managerAuditDept: 'Manager of audit department',
    auditReason: 'Audit reason',
    auditOrganization: 'Audit organization',
    auditedOrganization: 'Audited organization',
    distribution: 'Distribution',
    participants: 'Participants',
    name: 'Name',
    plantManager: 'Plant manager',
    city: 'City',
    postalCode: 'Postal code',
    email: 'E-Mail',
    phone: 'Phone',
    colAuditType: 'Auditor type',
    colName: 'Name',
    colCompany: 'Company',
    colDepartment: 'Department',
    addRow: 'Add row',
    separateEval: 'Separate evaluation for product and process development in P3 and P4',
    productGroup: 'Product(group)',
    processStep: 'Process(step)',
    helpP3P4: 'When enabled, track product vs process development separately per your audit rules.',
    helpProduct: 'Product or product group under assessment.',
    helpProcess: 'Process step under assessment.',
    clearHeader: 'Clear header',
    send: 'Send',
    yes: 'Yes',
    no: 'No',
    backHeader: '← Back to Header Form',
    jumpChapter: 'Jump by chapter',
    minReq: 'Minimum requirements relevant for assessment',
    examples: 'Examples for implementation',
    resultScore: 'Result score',
    notEval: 'n.e.',
    gptComparison: 'GPT Comparison',
    yourFinding: 'Your finding',
    gptSuggested: 'GPT suggested finding',
    gptInternalImported: 'GPT internal comment (from import)',
    keepMine: 'Keep mine',
    useGpt: 'Use GPT version',
    keepMineHint:
      'Sends your score, findings, and internal comments to ChatGPT as the locked auditor record, then clears the GPT draft fields here.',
    useGptHint:
      'Sends your score plus GPT finding and GPT internal comment to ChatGPT as the adopted record, then copies them into your official fields.',
    findingLockedUser:
      'Auditor wording sent to ChatGPT as locked. GPT draft fields cleared. Edit findings to unlock.',
    findingLockedGpt:
      'GPT wording sent to ChatGPT as adopted and copied into your fields. Edit findings or import again to unlock.',
    internalComment: 'Your internal comment',
    prev: '← Previous',
    next: 'Next →',
    startAudit: 'Continue to questions',
    sendQuestionGpt: 'Send to GPT',
    importGpt: 'Import from GPT',
    clearQuestion: 'Clear this question',
    resetAll: 'Reset entire audit',
    sectionHeading: 'Section heading',
    starQ: 'Star question',
    reportData: 'Report Data',
    auditDates: 'Audit date',
    auditItem: 'Audit item',
    organizationDetails: 'Organization details',
    auditedShift: 'Audited shift',
    qualityManager: 'Quality manager',
    signedByLine: 'Signed by',
    seniorManager: 'Senior manager',
    auditTeam: 'Audit team',
    colAuditorCert: 'Auditor type / Certificate no',
    colNameMail: 'Name / E-Mail',
    colCompanySigned: 'Company / Signed by',
    certificateNo: 'Certificate no',
    signedBy: 'Signed by',
    auditedOrgTitle: 'Audited organisation',
    supplierNumber: 'Supplier number',
    duns: 'D-U-N-S No',
    street1: 'Street 1',
    street2: 'Street 2',
    country: 'Country',
    internalAudit: 'Internal audit',
    productProcessTitle: 'Product(s/groups) and Process(es/steps)',
    result: 'Result',
    findings: 'Findings',
    internalComments: 'Internal comments',
    addFinding: '+ Finding',
    addInternalComment: '+ Internal comment',
    setAllNe: 'Set all n.e.',
    setAll10: 'Set all to 10',
    doNotAssess: 'Do not assess',
    tabHeaderData: 'Header data',
    tabQuestions: 'Questions',
    gptAssistant: 'GPT assistant',
    disclaimer:
      'Do not paste regulated or customer-confidential data unless your organisation permits use of ChatGPT for that data.',
  },
  de: {
    headerData: 'Kopfdaten',
    reportName: 'Berichtsname',
    orderNo: 'Auftragsnr.',
    reportDateStart: 'Berichtsdatum (Start)',
    reportDateEnd: 'Berichtsdatum (Ende)',
    managerAuditDept: 'Leiter Audit-Abteilung',
    auditReason: 'Auditgrund',
    auditOrganization: 'Auditorganisation',
    auditedOrganization: 'Auditierte Organisation',
    distribution: 'Verteiler',
    participants: 'Teilnehmer',
    name: 'Name',
    plantManager: 'Werksleitung',
    city: 'Stadt',
    postalCode: 'PLZ',
    email: 'E-Mail',
    phone: 'Telefon',
    colAuditType: 'Audittyp',
    colName: 'Name',
    colCompany: 'Firma',
    colDepartment: 'Abteilung',
    addRow: 'Zeile hinzufügen',
    separateEval: 'Getrennte Bewertung für Produkt- und Prozessentwicklung in P3 und P4',
    productGroup: 'Produkt(gruppe)',
    processStep: 'Prozess(schritt)',
    helpP3P4: 'Nach internen Regeln Produkt- vs. Prozessentwicklung getrennt führen.',
    helpProduct: 'Bewertetes Produkt oder Produktgruppe.',
    helpProcess: 'Bewerteter Prozessschritt.',
    clearHeader: 'Kopfdaten leeren',
    send: 'Senden',
    yes: 'Ja',
    no: 'Nein',
    backHeader: '← Zurück zum Kopf',
    jumpChapter: 'Kapitel springen',
    minReq: 'Mindestanforderungen für die Bewertung',
    examples: 'Umsetzungsbeispiele',
    resultScore: 'Ergebnisbewertung',
    notEval: 'n.b.',
    gptComparison: 'GPT-Vergleich',
    yourFinding: 'Ihr Befund',
    gptSuggested: 'GPT-Vorschlag',
    gptInternalImported: 'GPT-interner Kommentar (aus Import)',
    keepMine: 'Meinen behalten',
    useGpt: 'GPT-Version übernehmen',
    keepMineHint:
      'Sendet Punktzahl, Feststellungen und interne Kommentare an ChatGPT als festgeschriebenen Auditor-Stand und leert hier die GPT-Entwurfsfelder.',
    useGptHint:
      'Sendet Punktzahl sowie GPT-Befund und GPT-internen Kommentar an ChatGPT als übernommenen Stand und überträgt sie in Ihre offiziellen Felder.',
    findingLockedUser:
      'Auditor-Text an ChatGPT gesendet (festgeschrieben). GPT-Entwurf geleert. Bearbeiten zum Entsperren.',
    findingLockedGpt:
      'GPT-Text an ChatGPT gesendet und in Ihre Felder übernommen. Bearbeiten oder erneut importieren zum Entsperren.',
    internalComment: 'Interner Kommentar',
    prev: '← Zurück',
    next: 'Weiter →',
    startAudit: 'Zu den Fragen',
    sendQuestionGpt: 'An GPT senden',
    importGpt: 'Von GPT importieren',
    clearQuestion: 'Diese Frage leeren',
    resetAll: 'Gesamtes Audit zurücksetzen',
    sectionHeading: 'Abschnittsüberschrift',
    starQ: 'Sternfrage',
    reportData: 'Berichtsdaten',
    auditDates: 'Auditdatum',
    auditItem: 'Auditgegenstand',
    organizationDetails: 'Organisationsdetails',
    auditedShift: 'Auditierte Schicht',
    qualityManager: 'Qualitätsmanager',
    signedByLine: 'Unterschrieben von',
    seniorManager: 'Senior Manager',
    auditTeam: 'Auditteam',
    colAuditorCert: 'Auditorentyp / Zertifikatsnr.',
    colNameMail: 'Name / E-Mail',
    colCompanySigned: 'Firma / Unterschrift',
    certificateNo: 'Zertifikatsnr.',
    signedBy: 'Unterschrieben',
    auditedOrgTitle: 'Auditierte Organisation',
    supplierNumber: 'Lieferantennummer',
    duns: 'D-U-N-S-Nr.',
    street1: 'Straße 1',
    street2: 'Straße 2',
    country: 'Land',
    internalAudit: 'Internes Audit',
    productProcessTitle: 'Produkt(e/gruppen) und Prozess(e/schritte)',
    result: 'Ergebnis',
    findings: 'Feststellungen',
    internalComments: 'Interne Kommentare',
    addFinding: '+ Feststellung',
    addInternalComment: '+ Interner Kommentar',
    setAllNe: 'Alle n.b. setzen',
    setAll10: 'Alle auf 10',
    doNotAssess: 'Nicht bewerten',
    tabHeaderData: 'Kopfdaten',
    tabQuestions: 'Fragen',
    gptAssistant: 'GPT-Assistent',
    disclaimer:
      'Keine regulierten oder kundenvertraulichen Daten einfügen, sofern intern nicht freigegeben.',
  },
} as const;

export type UiLang = keyof typeof ui;
